import Foundation

// MARK: - CustomerPackV1
//
// Decision-first customer recommendation pack.
//
// Generated by Atlas Mind after processing a field survey.
// Consumed by the iOS app to present the recommendation to the homeowner.
//
// Design rules:
//   • One CustomerPackV1 = one property's complete recommendation.
//   • Atlas Mind writes this; Atlas Scan reads and displays it.
//   • No marketing claims — all outcomes must derive from survey data.
//   • Tone is confident and direct, not cautious or hedging.
//   • Wire format: JSON, camelCase keys.
//
// Section order (in display order):
//   1. decision       — one clear system recommendation
//   2. whyThisSystem  — physics translated to outcomes
//   3. antiDefault    — why the simpler option is worse
//   4. customerBenefits — tangible daily-life improvements
//   5. fullSystem     — every component and why it matters
//   6. dailyUse       — real-life scenarios
//   7. futurePath     — upgrade options this system enables
//   8. close          — final statement and next step

// MARK: - CustomerPackV1

/// Decision-first recommendation pack delivered to the homeowner.
///
/// Contains eight structured sections that guide the homeowner through
/// the decision journey: from the recommended system through to next steps.
/// Produced by Atlas Mind; displayed by Atlas Scan.
public struct CustomerPackV1: Codable, Sendable {

    // MARK: Schema identity

    /// Always `"1.0"` for this version of the contract.
    public let schemaVersion: String

    // MARK: Visit identity

    /// Cross-system visit identifier.
    public let visitId: String

    /// Engineer-assigned visit / job reference (e.g. `"JOB-2025-0042"`).
    public let visitReference: String

    /// Property address; nil when not captured.
    public let propertyAddress: String?

    /// Customer name; nil when not captured.
    public let customerName: String?

    /// ISO-8601 timestamp of when this pack was generated.
    public let generatedAt: String

    // MARK: Sections (in display order)

    /// Section 1 — The decision: one clear, unambiguous system recommendation.
    public let decision: CustomerPackDecisionV1

    /// Section 2 — Why this system: physics translated to outcomes, no raw numbers.
    public let whyThisSystem: CustomerPackWhyV1

    /// Section 3 — What happens if you don't: the honest anti-default argument.
    public let antiDefault: CustomerPackAntiDefaultV1

    /// Section 4 — What changes for you: tangible daily-life benefits.
    public let customerBenefits: CustomerPackBenefitsV1

    /// Section 5 — The full system: every component explained.
    public let fullSystem: CustomerPackFullSystemV1

    /// Section 6 — Daily use: how the system behaves in real-life scenarios.
    public let dailyUse: CustomerPackDailyUseV1

    /// Section 7 — Future path: upgrade options this system makes possible.
    public let futurePath: CustomerPackFuturePathV1

    /// Section 8 — Close: final statement and confirmed next step.
    public let close: CustomerPackCloseV1

    // MARK: Init

    public init(
        visitId: String,
        visitReference: String,
        propertyAddress: String? = nil,
        customerName: String? = nil,
        generatedAt: String,
        decision: CustomerPackDecisionV1,
        whyThisSystem: CustomerPackWhyV1,
        antiDefault: CustomerPackAntiDefaultV1,
        customerBenefits: CustomerPackBenefitsV1,
        fullSystem: CustomerPackFullSystemV1,
        dailyUse: CustomerPackDailyUseV1,
        futurePath: CustomerPackFuturePathV1,
        close: CustomerPackCloseV1
    ) {
        self.schemaVersion = "1.0"
        self.visitId = visitId
        self.visitReference = visitReference
        self.propertyAddress = propertyAddress
        self.customerName = customerName
        self.generatedAt = generatedAt
        self.decision = decision
        self.whyThisSystem = whyThisSystem
        self.antiDefault = antiDefault
        self.customerBenefits = customerBenefits
        self.fullSystem = fullSystem
        self.dailyUse = dailyUse
        self.futurePath = futurePath
        self.close = close
    }
}

// MARK: - Section 1: Decision

/// The single, unambiguous system recommendation.
///
/// No alternatives presented at this stage — one clear outcome statement.
public struct CustomerPackDecisionV1: Codable, Sendable {

    /// The recommended system name (e.g. `"Unvented cylinder system with high-efficiency boiler"`).
    public let systemName: String

    /// The outcome statement — confident and direct.
    ///
    /// Example: `"This is the right system for your home."`
    public let outcomeStatement: String

    /// One-sentence explanation of why this is the correct choice for this property.
    public let rationale: String

    public init(systemName: String, outcomeStatement: String, rationale: String) {
        self.systemName = systemName
        self.outcomeStatement = outcomeStatement
        self.rationale = rationale
    }
}

// MARK: - Section 2: Why this system

/// Physics translated into outcomes — no raw heat-loss numbers.
public struct CustomerPackWhyV1: Codable, Sendable {

    /// Headline behaviour statement.
    ///
    /// Example: `"Your home needs steady, reliable heat — not bursts."`
    public let behaviourStatement: String

    /// Two to four outcome-linked reasons why this system fits this property.
    public let reasons: [CustomerPackReasonV1]

    public init(behaviourStatement: String, reasons: [CustomerPackReasonV1]) {
        self.behaviourStatement = behaviourStatement
        self.reasons = reasons
    }
}

/// One physics-to-outcome reason.
public struct CustomerPackReasonV1: Codable, Sendable {

    /// Short label (e.g. `"Consistent heat delivery"`).
    public let label: String

    /// One sentence linking observed system behaviour to a customer outcome.
    public let explanation: String

    public init(label: String, explanation: String) {
        self.label = label
        self.explanation = explanation
    }
}

// MARK: - Section 3: Anti-default

/// Why the simpler or cheaper alternative is the worse outcome.
///
/// Honest — not alarmist. All consequences must be derivable from survey data.
public struct CustomerPackAntiDefaultV1: Codable, Sendable {

    /// The alternative being compared against (e.g. `"A like-for-like boiler swap"`).
    public let alternativeLabel: String

    /// Two to four honest consequences of taking the default option.
    public let consequences: [String]

    public init(alternativeLabel: String, consequences: [String]) {
        self.alternativeLabel = alternativeLabel
        self.consequences = consequences
    }
}

// MARK: - Section 4: Customer benefits

/// Tangible daily-life improvements the customer will notice.
public struct CustomerPackBenefitsV1: Codable, Sendable {

    /// Headline benefit statement.
    public let headline: String

    /// Four to six specific, concrete benefits.
    public let benefits: [CustomerPackBenefitV1]

    public init(headline: String, benefits: [CustomerPackBenefitV1]) {
        self.headline = headline
        self.benefits = benefits
    }
}

/// One concrete customer benefit.
public struct CustomerPackBenefitV1: Codable, Sendable {

    /// SF Symbol name for the benefit icon (e.g. `"drop.fill"`, `"thermometer.sun.fill"`).
    public let symbolName: String

    /// Short label (e.g. `"Hot water that doesn't run out"`).
    public let label: String

    public init(symbolName: String, label: String) {
        self.symbolName = symbolName
        self.label = label
    }
}

// MARK: - Section 5: Full system

/// Every component included in the installation and why it matters.
public struct CustomerPackFullSystemV1: Codable, Sendable {

    /// Headline — "This isn't just a boiler replacement."
    public let headline: String

    /// What the full system achieves (one to two sentences).
    public let summary: String

    /// Each component in the package.
    public let components: [CustomerPackComponentV1]

    /// Future-ready elements included in this installation (e.g. `"Pre-pipework for heat pump"`).
    public let futureReadyElements: [String]

    public init(
        headline: String,
        summary: String,
        components: [CustomerPackComponentV1],
        futureReadyElements: [String]
    ) {
        self.headline = headline
        self.summary = summary
        self.components = components
        self.futureReadyElements = futureReadyElements
    }
}

/// One component in the full system package.
public struct CustomerPackComponentV1: Codable, Sendable {

    /// Component category raw value (e.g. `"boiler"`, `"cylinder"`, `"controls"`, `"pipework"`).
    public let category: String

    /// Specific product or description (e.g. `"Mixergy smart unvented cylinder"`).
    public let description: String

    /// One-sentence explanation of what this component does for the customer.
    public let purpose: String

    public init(category: String, description: String, purpose: String) {
        self.category = category
        self.description = description
        self.purpose = purpose
    }
}

// MARK: - Section 6: Daily use

/// How the system behaves in real-life household scenarios.
public struct CustomerPackDailyUseV1: Codable, Sendable {

    /// Two to four short scenario descriptions.
    public let scenarios: [CustomerPackScenarioV1]

    public init(scenarios: [CustomerPackScenarioV1]) {
        self.scenarios = scenarios
    }
}

/// One daily-use scenario.
public struct CustomerPackScenarioV1: Codable, Sendable {

    /// Short scenario label (e.g. `"Morning rush"`).
    public let label: String

    /// What the customer experiences (e.g. `"Hot water for everyone — no waiting, no cold drop"`).
    public let outcome: String

    public init(label: String, outcome: String) {
        self.label = label
        self.outcome = outcome
    }
}

// MARK: - Section 7: Future path

/// Upgrade options that this system makes possible.
public struct CustomerPackFuturePathV1: Codable, Sendable {

    /// Statement of what works today (e.g. `"System works at full performance from day one."`).
    public let todayStatement: String

    /// Future upgrade options this system enables.
    public let upgradeOptions: [CustomerPackUpgradeOptionV1]

    public init(todayStatement: String, upgradeOptions: [CustomerPackUpgradeOptionV1]) {
        self.todayStatement = todayStatement
        self.upgradeOptions = upgradeOptions
    }
}

/// One future upgrade option enabled by the installed system.
public struct CustomerPackUpgradeOptionV1: Codable, Sendable {

    /// Upgrade label (e.g. `"Heat pump"`, `"Solar thermal"`, `"Battery storage"`).
    public let label: String

    /// One sentence explaining how this installation enables the upgrade.
    public let enabledBy: String

    public init(label: String, enabledBy: String) {
        self.label = label
        self.enabledBy = enabledBy
    }
}

// MARK: - Section 8: Close

/// Final outcome statement and confirmed next step.
public struct CustomerPackCloseV1: Codable, Sendable {

    /// Closing statement (e.g. `"This is the best outcome for your home."`).
    public let closingStatement: String

    /// The next step label (e.g. `"Installation planning"`).
    public let nextStepLabel: String

    /// One sentence describing what the next step involves.
    public let nextStepDescription: String

    public init(
        closingStatement: String,
        nextStepLabel: String,
        nextStepDescription: String
    ) {
        self.closingStatement = closingStatement
        self.nextStepLabel = nextStepLabel
        self.nextStepDescription = nextStepDescription
    }
}
