import Foundation

// MARK: - HardwareRegistryV1
//
// Master registry of static appliance definitions bundled with the contract.
//
// Architecture:
//   • `MasterHardwareRegistry` is the compile-time-constant baseline shipped
//     with every build.  It mirrors `ApplianceProfileLibrary` in AtlasScan but
//     lives here so both Atlas Scan (iOS) and Atlas Mind (PWA) share one truth.
//   • `HardwarePatchV1` carries runtime overrides produced by the Mind "Editor"
//     and is attached to a `VisitHandoffPackV1` when Mind sends a survey to Scan.
//
// Lookup pattern (preferred, highest-priority first):
//   1. Definitions from the `HardwarePatchV1` received in the visit handoff.
//   2. Definitions from the `MasterHardwareRegistry`.
//
// Wire format: JSON, camelCase keys, schemaVersion = 1.

// MARK: - HardwarePatchV1

/// A set of runtime appliance definition overrides produced by Atlas Mind and
/// carried inside a `VisitHandoffPackV1` when Mind dispatches a survey to Scan.
///
/// The iOS app merges these into its local registry, preferring patch definitions
/// over static ones when `modelId` keys collide.
public struct HardwarePatchV1: Codable, Sendable {

    // MARK: Schema identity

    /// Always `"hardware-patch"` — discriminator for the consuming app.
    public let kind: String

    /// Patch schema version; always `1` for this generation.
    public let schemaVersion: Int

    // MARK: Content

    /// Unique identifier for this patch (UUID string, generated by Mind).
    public let patchId: String

    /// Definitions that replace a static entry with the same `modelId`.
    public let overrides: [ApplianceDefinitionV1]

    /// Definitions for models not present in the static registry.
    public let additions: [ApplianceDefinitionV1]

    // MARK: Provenance

    /// ISO-8601 timestamp of when this patch was generated.
    public let generatedAt: String

    // MARK: Init

    public init(
        patchId: String,
        overrides: [ApplianceDefinitionV1],
        additions: [ApplianceDefinitionV1],
        generatedAt: String
    ) {
        self.kind = "hardware-patch"
        self.schemaVersion = 1
        self.patchId = patchId
        self.overrides = overrides
        self.additions = additions
        self.generatedAt = generatedAt
    }
}

// MARK: - HardwareRegistryV1

/// An in-memory registry of `ApplianceDefinitionV1` entries built from
/// the static master data and optionally merged with a runtime patch.
public struct HardwareRegistryV1: Sendable {

    // MARK: Entries

    /// All definitions in this registry, keyed by `modelId`.
    public private(set) var definitions: [String: ApplianceDefinitionV1]

    // MARK: Init

    /// Creates a registry from an ordered array of definitions.
    /// Duplicate `modelId` values are resolved by last-write-wins.
    public init(definitions: [ApplianceDefinitionV1]) {
        self.definitions = Dictionary(
            definitions.map { ($0.modelId, $0) },
            uniquingKeysWith: { _, last in last }
        )
    }

    // MARK: Lookup

    /// Returns the definition for the given `modelId`, or `nil`.
    public func definition(for modelId: String) -> ApplianceDefinitionV1? {
        definitions[modelId]
    }

    /// Returns all definitions whose `category` matches the given raw value.
    public func definitions(forCategory category: String) -> [ApplianceDefinitionV1] {
        definitions.values.filter { $0.category == category }
            .sorted { $0.displayName < $1.displayName }
    }

    // MARK: Patch merging

    /// Returns a new registry that applies `patch` on top of the current entries.
    ///
    /// Overrides replace static definitions with matching `modelId`;
    /// additions are inserted for new model IDs.
    public func applying(_ patch: HardwarePatchV1) -> HardwareRegistryV1 {
        var merged = definitions
        for override in patch.overrides {
            merged[override.modelId] = override
        }
        for addition in patch.additions {
            merged[addition.modelId] = addition
        }
        var result = HardwareRegistryV1(definitions: [])
        result.definitions = merged
        return result
    }
}

// MARK: - MasterHardwareRegistry

/// The static baseline registry bundled with the contract.
///
/// Data mirrors `ApplianceProfileLibrary` in AtlasScan but expressed using the
/// shared `ApplianceDefinitionV1` contract type so both apps share one truth.
/// Dimensions are approximate guidance values in millimetres.
public enum MasterHardwareRegistry {

    // MARK: Registry accessor

    /// The compiled master registry.
    public static let registry: HardwareRegistryV1 = HardwareRegistryV1(
        definitions: boilerDefinitions + cylinderDefinitions + manifoldDefinitions + radiatorDefinitions
    )

    // MARK: Boilers

    public static let boilerDefinitions: [ApplianceDefinitionV1] = [
        ApplianceDefinitionV1(
            modelId:     "combi_generic",
            brand:       "Generic",
            family:      "Combi Boiler",
            displayName: "Boiler placeholder — needs identification (standard)",
            category:    "boiler",
            dimensions:  ApplianceDimensionsV1(widthMm: 600, depthMm: 500, heightMm: 750),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 300,
                frontMm:           600,
                sideMm:            150,
                rearMm:             50,
                topMm:             200,
                minCeilingHeightMm: 2000
            ),
            guidanceNote: "Typical wall-hung combi. Verify manufacturer spec for exact clearances."
        ),
        ApplianceDefinitionV1(
            modelId:     "combi_compact",
            brand:       "Generic",
            family:      "Combi Boiler",
            displayName: "Boiler placeholder — needs identification (compact)",
            category:    "boiler",
            dimensions:  ApplianceDimensionsV1(widthMm: 440, depthMm: 360, heightMm: 700),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 300,
                frontMm:           600,
                sideMm:            100,
                rearMm:             50,
                topMm:             200,
                minCeilingHeightMm: 2000
            ),
            guidanceNote: "Compact wall-hung combi. Smaller body but same front service clearance required."
        ),
        ApplianceDefinitionV1(
            modelId:     "system_generic",
            brand:       "Generic",
            family:      "System Boiler",
            displayName: "Generic system boiler",
            category:    "boiler",
            dimensions:  ApplianceDimensionsV1(widthMm: 700, depthMm: 500, heightMm: 800),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 300,
                frontMm:           600,
                sideMm:            150,
                rearMm:             50,
                topMm:             200,
                minCeilingHeightMm: 2000
            ),
            guidanceNote: "System boiler — typically wider than a combi. Check system pump clearance too."
        ),
        ApplianceDefinitionV1(
            modelId:     "regular_generic",
            brand:       "Generic",
            family:      "Regular Boiler",
            displayName: "Regular (heat-only) boiler",
            category:    "boiler",
            dimensions:  ApplianceDimensionsV1(widthMm: 700, depthMm: 550, heightMm: 800),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 350,
                frontMm:           700,
                sideMm:            200,
                rearMm:             50,
                topMm:             200,
                minCeilingHeightMm: 2000
            ),
            guidanceNote: "Regular boiler. Typically more side room needed for pipework and zone valves."
        ),
        ApplianceDefinitionV1(
            modelId:     "worcester_4000_combi_30",
            brand:       "Worcester Bosch",
            family:      "Combi Boiler",
            displayName: "4000 Series Combi 30kW",
            category:    "boiler",
            dimensions:  ApplianceDimensionsV1(widthMm: 440, depthMm: 360, heightMm: 750),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 300,
                frontMm:           600,
                sideMm:            100,
                rearMm:             50,
                topMm:             200,
                minCeilingHeightMm: 2000
            ),
            guidanceNote: "Worcester Bosch 4000 Series — compact wall-hung combi. Refer to installation manual for full clearance requirements."
        ),
        ApplianceDefinitionV1(
            modelId:     "worcester_8000_style_combi_30",
            brand:       "Worcester Bosch",
            family:      "Combi Boiler",
            displayName: "8000 Style Combi 30kW",
            category:    "boiler",
            dimensions:  ApplianceDimensionsV1(widthMm: 450, depthMm: 380, heightMm: 800),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 300,
                frontMm:           600,
                sideMm:            100,
                rearMm:             50,
                topMm:             200,
                minCeilingHeightMm: 2000
            ),
            guidanceNote: "Worcester Bosch 8000 Style — premium combi. Confirm flue position before install."
        ),
        ApplianceDefinitionV1(
            modelId:     "vaillant_ecotec_plus_combi_30",
            brand:       "Vaillant",
            family:      "Combi Boiler",
            displayName: "ecoTEC Plus Combi 30kW",
            category:    "boiler",
            dimensions:  ApplianceDimensionsV1(widthMm: 440, depthMm: 380, heightMm: 720),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 300,
                frontMm:           600,
                sideMm:            100,
                rearMm:             50,
                topMm:             200,
                minCeilingHeightMm: 2000
            ),
            guidanceNote: "Vaillant ecoTEC Plus — check condensate drain route (requires 52 mm trap clearance)."
        ),
        ApplianceDefinitionV1(
            modelId:     "ideal_logic_plus_combi_30",
            brand:       "Ideal",
            family:      "Combi Boiler",
            displayName: "Logic Plus Combi 30kW",
            category:    "boiler",
            dimensions:  ApplianceDimensionsV1(widthMm: 400, depthMm: 340, heightMm: 700),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 300,
                frontMm:           600,
                sideMm:            100,
                rearMm:             50,
                topMm:             200,
                minCeilingHeightMm: 2000
            ),
            guidanceNote: "Ideal Logic Plus — compact footprint. Verify case dimension from installer sheet."
        ),
    ]

    // MARK: Cylinders

    public static let cylinderDefinitions: [ApplianceDefinitionV1] = [
        ApplianceDefinitionV1(
            modelId:     "gledhill_open_vented_copper_117l",
            brand:       "Gledhill",
            family:      "Open Vented Cylinder",
            displayName: "Copper open vented 117L",
            category:    "cylinder",
            dimensions:  ApplianceDimensionsV1(widthMm: 450, depthMm: 450, heightMm: 1100),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 250,
                frontMm:           500,
                sideMm:            100,
                rearMm:             50,
                topMm:             300,
                minCeilingHeightMm: 1800
            ),
            guidanceNote: "Open vented cylinder. Keep feed/expansion path and overflow route accessible."
        ),
        ApplianceDefinitionV1(
            modelId:     "gledhill_unvented_stainless_210l",
            brand:       "Gledhill",
            family:      "Unvented Cylinder",
            displayName: "Stainless unvented 210L",
            category:    "cylinder",
            dimensions:  ApplianceDimensionsV1(widthMm: 550, depthMm: 550, heightMm: 1470),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 250,
                frontMm:           500,
                sideMm:            100,
                rearMm:             50,
                topMm:             300,
                minCeilingHeightMm: 1900
            ),
            guidanceNote: "Unvented cylinder (G3). Confirm tundish/relief discharge and service-valve access."
        ),
        ApplianceDefinitionV1(
            modelId:     "gledhill_boilermate_a_classic",
            brand:       "Gledhill",
            family:      "Thermal Store",
            displayName: "BoilerMate A-Class thermal store",
            category:    "cylinder",
            dimensions:  ApplianceDimensionsV1(widthMm: 600, depthMm: 600, heightMm: 1750),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 300,
                frontMm:           600,
                sideMm:            100,
                rearMm:             50,
                topMm:             350,
                minCeilingHeightMm: 2000
            ),
            guidanceNote: "Thermal store / BoilerMate-style unit. Verify store type before downstream sizing logic."
        ),
        ApplianceDefinitionV1(
            modelId:     "mixergy_direct_unvented_210l",
            brand:       "Mixergy",
            family:      "Smart Cylinder",
            displayName: "Direct smart cylinder 210L (unvented)",
            category:    "cylinder",
            dimensions:  ApplianceDimensionsV1(widthMm: 550, depthMm: 550, heightMm: 1450),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 250,
                frontMm:           500,
                sideMm:            100,
                rearMm:             50,
                topMm:             300,
                minCeilingHeightMm: 1900
            ),
            guidanceNote: "Mixergy direct (unvented). Keep controls and immersion access clear."
        ),
        ApplianceDefinitionV1(
            modelId:     "mixergy_indirect_unvented_210l",
            brand:       "Mixergy",
            family:      "Smart Cylinder",
            displayName: "Indirect smart cylinder 210L (unvented)",
            category:    "cylinder",
            dimensions:  ApplianceDimensionsV1(widthMm: 550, depthMm: 550, heightMm: 1500),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 250,
                frontMm:           500,
                sideMm:            100,
                rearMm:             50,
                topMm:             300,
                minCeilingHeightMm: 1900
            ),
            guidanceNote: "Mixergy indirect cylinder with coil. Record coil arrangement for heat source pairing."
        ),
        ApplianceDefinitionV1(
            modelId:     "mixergy_hp_ready_indirect_250l",
            brand:       "Mixergy",
            family:      "Smart Cylinder",
            displayName: "Heat-pump-ready indirect 250L (unvented)",
            category:    "cylinder",
            dimensions:  ApplianceDimensionsV1(widthMm: 600, depthMm: 600, heightMm: 1700),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 300,
                frontMm:           600,
                sideMm:            100,
                rearMm:             50,
                topMm:             300,
                minCeilingHeightMm: 2000
            ),
            guidanceNote: "HP-ready smart cylinder with larger coil volume. Confirm vented vs unvented setup explicitly."
        ),
        ApplianceDefinitionV1(
            modelId:     "cylinder_placeholder_manual",
            brand:       "Unknown",
            family:      "Unknown / Manual Cylinder",
            displayName: "Cylinder placeholder — needs identification",
            category:    "cylinder",
            dimensions:  ApplianceDimensionsV1(widthMm: 500, depthMm: 500, heightMm: 1200),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 250,
                frontMm:           500,
                sideMm:            100,
                rearMm:             50,
                topMm:             300,
                minCeilingHeightMm: 1800
            ),
            guidanceNote: "Placeholder cylinder entry. Engineer identification required before customer-visible output."
        ),
    ]

    // MARK: Manifolds

    public static let manifoldDefinitions: [ApplianceDefinitionV1] = [
        ApplianceDefinitionV1(
            modelId:     "manifold_ufh_small",
            brand:       "Generic",
            family:      "UFH Manifold",
            displayName: "Small UFH manifold (≤ 6 loops)",
            category:    "manifold",
            dimensions:  ApplianceDimensionsV1(widthMm: 400, depthMm: 150, heightMm: 250),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 300,
                frontMm:           600,
                sideMm:            100,
                rearMm:               0,
                topMm:             150,
                minCeilingHeightMm: 1800
            ),
            guidanceNote: "Small manifold up to 6 UFH loops. Allow front access for flow/return valves and actuators."
        ),
        ApplianceDefinitionV1(
            modelId:     "manifold_ufh_standard",
            brand:       "Generic",
            family:      "UFH Manifold",
            displayName: "Standard UFH manifold (7–12 loops)",
            category:    "manifold",
            dimensions:  ApplianceDimensionsV1(widthMm: 600, depthMm: 150, heightMm: 250),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 300,
                frontMm:           600,
                sideMm:            100,
                rearMm:               0,
                topMm:             150,
                minCeilingHeightMm: 1800
            ),
            guidanceNote: "Standard manifold up to 12 loops. Check cabinet width if the manifold is to be boxed in."
        ),
        ApplianceDefinitionV1(
            modelId:     "manifold_ufh_large",
            brand:       "Generic",
            family:      "UFH Manifold",
            displayName: "Large UFH manifold (13+ loops)",
            category:    "manifold",
            dimensions:  ApplianceDimensionsV1(widthMm: 800, depthMm: 150, heightMm: 250),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm: 300,
                frontMm:           600,
                sideMm:            100,
                rearMm:               0,
                topMm:             150,
                minCeilingHeightMm: 1800
            ),
            guidanceNote: "Large manifold for 13+ loops. Significant wall width required — check available run."
        ),
    ]

    // MARK: Radiators

    public static let radiatorDefinitions: [ApplianceDefinitionV1] = [
        ApplianceDefinitionV1(
            modelId:     "radiator_compact",
            brand:       "Generic",
            family:      "Panel Radiator",
            displayName: "Compact radiator (up to 600 mm)",
            category:    "radiator",
            dimensions:  ApplianceDimensionsV1(widthMm: 550, depthMm: 120, heightMm: 600),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm:  30,
                frontMm:            50,
                sideMm:             50,
                rearMm:              0,
                topMm:              50,
                minCeilingHeightMm: 1500
            ),
            guidanceNote: nil
        ),
        ApplianceDefinitionV1(
            modelId:     "radiator_standard",
            brand:       "Generic",
            family:      "Panel Radiator",
            displayName: "Standard radiator (600–900 mm)",
            category:    "radiator",
            dimensions:  ApplianceDimensionsV1(widthMm: 750, depthMm: 120, heightMm: 600),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm:  30,
                frontMm:            50,
                sideMm:             50,
                rearMm:              0,
                topMm:              50,
                minCeilingHeightMm: 1500
            ),
            guidanceNote: nil
        ),
        ApplianceDefinitionV1(
            modelId:     "radiator_wide",
            brand:       "Generic",
            family:      "Panel Radiator",
            displayName: "Wide radiator (900–1200 mm)",
            category:    "radiator",
            dimensions:  ApplianceDimensionsV1(widthMm: 1050, depthMm: 120, heightMm: 600),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm:  30,
                frontMm:            50,
                sideMm:             50,
                rearMm:              0,
                topMm:              50,
                minCeilingHeightMm: 1500
            ),
            guidanceNote: "Wide radiator — check available wall run. Ensure no obstructions at either end."
        ),
        ApplianceDefinitionV1(
            modelId:     "radiator_double_panel",
            brand:       "Generic",
            family:      "Double Panel Radiator",
            displayName: "Double panel radiator",
            category:    "radiator",
            dimensions:  ApplianceDimensionsV1(widthMm: 600, depthMm: 180, heightMm: 600),
            clearanceRules: ApplianceClearanceRulesV1(
                installMinFrontMm:  30,
                frontMm:            50,
                sideMm:             50,
                rearMm:              0,
                topMm:              50,
                minCeilingHeightMm: 1500
            ),
            guidanceNote: "Double panel — deeper than standard. Check against furniture and window sill depth."
        ),
    ]
}
